
import { Inter, Lato, Montserrat } from 'next/font/google'
import './globals.css'
import Header from './components/Header/Header'
import Footer from './components/Footer/Footer'


const inter = Inter({ subsets: ['latin'] })
// const lato = Lato({weight:[400,700]}, {subsets: ['latin']})
// const montserrat = Montserrat({ weights: [400, 700],subsets: ['latin'] })

export const metadata = {
  title: 'Doctor Who',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='body'>
        <Header />
        {children}
        
        <Footer/>
  
        </body>
    </html>
  )
}
